package clases;
// Generated 7 feb 2022 13:39:47 by Hibernate Tools 5.5.7.Final

/**
 * Pasajeros generated by hbm2java
 */
public class Pasajeros implements java.io.Serializable {

	private PasajerosId id;
	private Vuelos vuelos;
	private String tipoPlaza;
	private String fumador;

	public Pasajeros() {
	}

	public Pasajeros(PasajerosId id, Vuelos vuelos) {
		this.id = id;
		this.vuelos = vuelos;
	}

	public Pasajeros(PasajerosId id, Vuelos vuelos, String tipoPlaza, String fumador) {
		this.id = id;
		this.vuelos = vuelos;
		this.tipoPlaza = tipoPlaza;
		this.fumador = fumador;
	}

	public PasajerosId getId() {
		return this.id;
	}

	public void setId(PasajerosId id) {
		this.id = id;
	}

	public Vuelos getVuelos() {
		return this.vuelos;
	}

	public void setVuelos(Vuelos vuelos) {
		this.vuelos = vuelos;
	}

	public String getTipoPlaza() {
		return this.tipoPlaza;
	}

	public void setTipoPlaza(String tipoPlaza) {
		this.tipoPlaza = tipoPlaza;
	}

	public String getFumador() {
		return this.fumador;
	}

	public void setFumador(String fumador) {
		this.fumador = fumador;
	}

}
