package clases;
// Generated 7 feb 2022 13:39:47 by Hibernate Tools 5.5.7.Final

/**
 * PasajerosId generated by hbm2java
 */
public class PasajerosId implements java.io.Serializable {

	private int num;
	private String codVuelo;

	public PasajerosId() {
	}

	public PasajerosId(int num, String codVuelo) {
		this.num = num;
		this.codVuelo = codVuelo;
	}

	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	public String getCodVuelo() {
		return this.codVuelo;
	}

	public void setCodVuelo(String codVuelo) {
		this.codVuelo = codVuelo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PasajerosId))
			return false;
		PasajerosId castOther = (PasajerosId) other;

		return (this.getNum() == castOther.getNum())
				&& ((this.getCodVuelo() == castOther.getCodVuelo()) || (this.getCodVuelo() != null
						&& castOther.getCodVuelo() != null && this.getCodVuelo().equals(castOther.getCodVuelo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNum();
		result = 37 * result + (getCodVuelo() == null ? 0 : this.getCodVuelo().hashCode());
		return result;
	}

}
