package clases;
// Generated 7 feb 2022 13:39:47 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Vuelos generated by hbm2java
 */
public class Vuelos implements java.io.Serializable {

	private String codVuelo;
	private String horaSalida;
	private String destino;
	private String procedencia;
	private Integer plazasFumador;
	private Integer plazasNoFumador;
	private Integer plazasTurista;
	private Integer plazasPrimera;
	private Set pasajeroses = new HashSet(0);

	public Vuelos() {
	}

	public Vuelos(String codVuelo) {
		this.codVuelo = codVuelo;
	}

	public Vuelos(String codVuelo, String horaSalida, String destino, String procedencia, Integer plazasFumador,
			Integer plazasNoFumador, Integer plazasTurista, Integer plazasPrimera, Set pasajeroses) {
		this.codVuelo = codVuelo;
		this.horaSalida = horaSalida;
		this.destino = destino;
		this.procedencia = procedencia;
		this.plazasFumador = plazasFumador;
		this.plazasNoFumador = plazasNoFumador;
		this.plazasTurista = plazasTurista;
		this.plazasPrimera = plazasPrimera;
		this.pasajeroses = pasajeroses;
	}

	public String getCodVuelo() {
		return this.codVuelo;
	}

	public void setCodVuelo(String codVuelo) {
		this.codVuelo = codVuelo;
	}

	public String getHoraSalida() {
		return this.horaSalida;
	}

	public void setHoraSalida(String horaSalida) {
		this.horaSalida = horaSalida;
	}

	public String getDestino() {
		return this.destino;
	}

	public void setDestino(String destino) {
		this.destino = destino;
	}

	public String getProcedencia() {
		return this.procedencia;
	}

	public void setProcedencia(String procedencia) {
		this.procedencia = procedencia;
	}

	public Integer getPlazasFumador() {
		return this.plazasFumador;
	}

	public void setPlazasFumador(Integer plazasFumador) {
		this.plazasFumador = plazasFumador;
	}

	public Integer getPlazasNoFumador() {
		return this.plazasNoFumador;
	}

	public void setPlazasNoFumador(Integer plazasNoFumador) {
		this.plazasNoFumador = plazasNoFumador;
	}

	public Integer getPlazasTurista() {
		return this.plazasTurista;
	}

	public void setPlazasTurista(Integer plazasTurista) {
		this.plazasTurista = plazasTurista;
	}

	public Integer getPlazasPrimera() {
		return this.plazasPrimera;
	}

	public void setPlazasPrimera(Integer plazasPrimera) {
		this.plazasPrimera = plazasPrimera;
	}

	public Set getPasajeroses() {
		return this.pasajeroses;
	}

	public void setPasajeroses(Set pasajeroses) {
		this.pasajeroses = pasajeroses;
	}

}
